# Generated by Django 5.0.1 on 2024-02-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0075_deliveryagent_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
