# Generated by Django 5.0.1 on 2024-02-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0077_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
