# Generated by Django 5.0.1 on 2024-02-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0078_certification_latitude_certification_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='location',
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
