# Generated by Django 5.0.1 on 2024-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0079_remove_deliveryagent_location_deliveryagent_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
    ]
