# Generated by Django 5.0.1 on 2024-02-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0080_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
    ]
