# Generated by Django 5.0.1 on 2024-02-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0081_billingdetails_latitude_billingdetails_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
