# Generated by Django 5.0.1 on 2024-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0087_orderitem_qr_scanned_orderitem_scanned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
